name: condo_connect
description: "Aplicativo de gestÃ£o condominial"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  cupertino_icons: ^1.0.8

  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4

  get_it: ^9.1.1
  google_fonts: ^6.3.2

  http: ^1.6.0

  injectable: ^2.7.0
  
  intl: ^0.20.2
  json_annotation: ^4.9.0



  shared_preferences: ^2.5.3

  url_launcher: ^6.3.2  
  

dev_dependencies:
  build_runner: ^2.7.1

  flutter_launcher_icons: ^0.14.4
  
  flutter_lints: ^6.0.0
  
  flutter_test:
    sdk: flutter
  
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.0
  test: ^1.26.2
  

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
